services:
  backend:
    build: ./backend
    container_name: adonis_backend
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talentos
      MYSQL_USER: talentos_user
      MYSQL_PASSWORD: talentos_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: