name: CI/CD Backend AdonisJS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: talentos
          MYSQL_USER: talentos_user
          MYSQL_PASSWORD: talentos_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        cd backend
        npm install

    - name: Run Migrations
      run: |
        cd backend
        node ace migration:run

    - name: Run Tests
      run: |
        cd backend
        npm run test